<?php

$push_notifications_default_option = [
    'PUSH_NOTIFICATION_SETTINGS_SENDING_WITH_STATUSES_TYPE_CODE' => 'ORDER_STATUS_DARK',
    'PUSH_NOTIFICATION_SETTINGS_SENDING_WHEN_ORDER_CHANGED_TYPE_CODE' => 'ORDER_CHANGED_DARK',
    'PUSH_NOTIFICATION_SETTINGS_SENDING_TO_ORDER_EVALUATE_TYPE_CODE' => 'ORDER_EVALUATE_DARK',
];
